---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortigate-lb-ctlr
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fortigate-lb-ctlr
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - list
  - get
- apiGroups: [""]
  resources:
  - services
  verbs:
  - list
  - get
  - update
  - patch
  - watch
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ipam.nexinto.com
  resources:
  - ipaddresses
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fortigate-lb-ctlr
subjects:
- kind: ServiceAccount
  name: fortigate-lb-ctlr
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: fortigate-lb-ctlr
